import { initializeApp } from "firebase/app";
import { getFirestore } from "firebase/firestore";
import { getAuth, GoogleAuthProvider } from "firebase/auth";

// Load configuration from the JSON file generated by AI Studio
const firebaseConfig = {
  projectId: "ordinal-gravity-wwjkk",
  appId: "1:613181401002:web:6b525dcd9f6ce0aa83edd3",
  apiKey: "AIzaSyDclVQq7xO20ZVlXHMIKMiMn49Yx_pppfk",
  authDomain: "ordinal-gravity-wwjkk.firebaseapp.com",
  firestoreDatabaseId: "ai-studio-civiclensglobal-cf05dc80-9e39-4db3-bfa8-d91427e36707",
  storageBucket: "ordinal-gravity-wwjkk.firebasestorage.app",
  messagingSenderId: "613181401002"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
export const db = getFirestore(app, firebaseConfig.firestoreDatabaseId);
export const auth = getAuth(app);
export const googleProvider = new GoogleAuthProvider();

